### ISSUE TITLE
PostgreSQL storage provider

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/globalstorage#137]

**Comment by nechaido** [comment]
@tshemsedinov I have a few questions:
* should we provide API for creating tables?
* do we have complete database schema specification?
* should we provide an ability to use existing pg transactions?

**Comment by nechaido** [comment]
One more question: do we have a complete specification for JSQL?

**Comment by belochub** [comment]
Duplicate of https://github.com/metarhia/globalstorage/issues/204.
