### ISSUE TITLE
CI fails after metatests updated

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/globalstorage#158]
See example: https://travis-ci.org/metarhia/globalstorage/jobs/417513067

**Comment by lundibundi** [comment]
@tshemsedinov I'll fix this, it is related to possibly incorrect mongo tests. They hang along the way. And also some issue seem to be present in current metatests version (this seems to be affected by the same issue https://github.com/metarhia/common/issues/169).

I just wanted to land https://github.com/metarhia/metatests/pull/66 first to rewrite them more elegantly with new functionality.
