### ISSUE TITLE
Implement RemoteProvider

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/globalstorage#213]
This provider will be created at the client-side and will be used as a database connection, but it will pass all requests to the server using JSTP and will instantiate RemoteCursors.
Refs: https://github.com/metarhia/globalstorage/issues/204

**Comment by Drawmet** [comment]
@tshemsedinov, Переасайнить надо на меня issue?

**Comment by nechaido** [comment]
@Drawmet it is better to use English in public repositories.
