### ISSUE TITLE
Change comments style

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/globalstorage#217]
Example before changes:
```
const row = (
  // Get dataset row
  ds // array of records, example: [ { Id: 1, Name: 'Marcus' } ]
  // Result: result array of records, example: [1, 'Marcus']
) => {
  const result = [];
  if (Array.isArray(ds) && ds.length > 0) {
    const obj = ds[0];
    ...
```
after changes:
```
// Get dataset row
//   ds - array of records, example: [ { Id: 1, Name: 'Marcus' } ]
// Result: result array of records, example: [1, 'Marcus']
const row = ds => {
  const result = [];
  if (Array.isArray(ds) && ds.length > 0) {
    const obj = ds[0];
    ...
```

**Comment by SemenchenkoVitaliy** [comment]
@tshemsedinov Does this apply to all repos or only this one?

**Comment by tshemsedinov** [comment]
Now paused, I'll make separate issues, because such changes may conflict with urgent changes

**Comment by belochub** [comment]
I am unpausing this since there are now almost no changes to the current public API of globalstorage that can cause conflicts.

**Comment by JuliaGerasymenko** [comment]
const col = (
  // Get dataset column
  ds, // array of records, example: [ { Id: 1 }, { Id: 2 }, { Id: 3 } ]
  field // optional, field name
  // Result: result array of records, example: [1, 2, 3]

Is it correct, if I'll change this way ?

// Get dataset column
//
// ds - <Object[]>
//
// Example: [ { Id: 1 }, { Id: 2 }, { Id: 3 } ]
//
// field - optional, field name
//
// Result: result <any[]>, example: [1, 2, 3]

**Comment by SemenchenkoVitaliy** [comment]
@JuliaGerasymenko please, wrap code blocks by using markdown syntax highlighting https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by SemenchenkoVitaliy** [comment]
@JuliaGerasymenko Every parameter should have an indentation of 2 spaces per each nesting level + one space at the beginning of every line. If function does not return anything you shouldn't add empty `Returns` as it doesn't give any information and therefore should be omited. The same goes for `Throws`. Also, it would be nice if you add type for each parameter if possible. In case if type doesn't matter you can put `any` type. In this particular case, however, it seems that `field` must be the `string` type.
```js
// Get dataset column
//   field - <string> field name, optional
//   ds - <Object[]> array of records, example: [ { Id: 1 }, { Id: 2 }, { Id: 3 } ]
//
// Example: [ { Id: 1 }, { Id: 2 }, { Id: 3 } ]
// Result: [1, 2, 3]
```

**Comment by SemenchenkoVitaliy** [comment]
Closed in https://github.com/metarhia/globalstorage/commit/29ecbe1ba824c0d33e498f40cbf9c26977a0ae51.
