### ISSUE TITLE
Update without specifying id/_id

### ISSUE THREAD

**Issue by belochub** [metarhia/GlobalStorage#25]
It would be great to have possibility to specify objects which must be changed on update without having to provide object with `id`/`_id` fields, because in cases, when the object is stored in memory without this fields or there are other omitted fields in this object, `find` method has to be called before calling `update`.

**Comment by tshemsedinov** [comment]
We can just add update method to cursor. See example:
```js
gs.find({ category: 'Person', city: 'Kiev' }).update({ lat: 50.4501, lon: 30.5234 });
```
It will pass update to mongodb or other storage provider, not getting dataset and integrating it in cursor.

**Comment by tshemsedinov** [comment]
FYI: @belochub, @DzyubSpirit 
This will be available after publishing new version to npm today
