### ISSUE TITLE
Fix item.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/globalstorage#253]
After upgrading to `metarhia-common@0.034` we can't call `hasOwnProperty` on a regular object `{ Id: 2, a: 1 }` from `lib/operations.js` because it have no `__proto__` and it's very strange. With `metarhia-commin@0.033` everything works well. In addition metatests returns 0 exit code and CI displays no fail indication.
See experimental PR https://github.com/metarhia/globalstorage/pull/252 with tho commits, first fails: bfcc87ff9e710d4d10aca5ef8ddc0980045c1999, second fixes: 28138ef1ec70288bd7e4ce53dabebd67fb30f165 but with obvious crutch.
I think this is because of the following changes: https://github.com/metarhia/common/commit/b2f7cf2f78bc7ecc5c6a8632390dddbc6c6d5cd9

See `npm t` output:
```js
 Test failed: count field test

        Type: unhandledExeption
     Message: item.hasOwnProperty is not a function
    Expected: undefined is undefined
      Actual: undefined is undefined
       Stack: TypeError: item.hasOwnProperty is not a function
            Array.forEach (<anonymous>)
            count (/lib/operations.js:71:13)
            jsql.forEach.operation (/lib/memory.cursor.js:40:19)
            Array.forEach (<anonymous>)
            process (/lib/memory.cursor.js:38:17)
            MemoryCursor.fetch (/lib/memory.cursor.js:57:7)
            ImperativeTest.metatests.test.test [as func] (/test/memory.js:85:6)
            Domain.funcDomain.run (/node_modules/metatests/lib/imperative-test.js:363:31)
            Domain.run (domain.js:343:14)
            ImperativeTest.runNow (/node_modules/metatests/lib/imperative-test.js:363:16)
            process.nextTick (/node_modules/metatests/lib/imperative-test.js:349:12)
```

**Comment by lundibundi** [comment]
Well, the PR you mentioned uses `Object.create(null)` which obviously won't have the mentioned method (or any other) as you set a prototype to null. The fix would be to use `{}` instead I think. But I don't know what was the initial reasoning behind setting `null` proto, so maybe that's not an option?
Also, perhaps `Object.assign(Object.create(null), obj)` would be better than creating a clean `{}`?
