### ISSUE TITLE
Record duplicates

### ISSUE THREAD

**Issue by olexande** [metarhia/globalstorage#54]
Резервные копии нужно сохранять обязательно так, что-бы резервные копии хранились на разных серверах от "оригинала" и при наличии "версий", то и разные версии на 1 ПК хранить нельзя.

Hadoop, если взять как пример кластерных решений в своих ФС "держат" минимум 3 копии одной и той же информации на разных физических серверах. С одной стороны это нужно для ускорения, с другой - для защиты от сбоев и в некоторой степени удешевления серверов (меньше нужна избыточность дисков).

**Comment by tshemsedinov** [comment]
We use English for github repos, please translate above.

We already discussed duplication mechanism, have you heard it on meetup?
